package com.example.digitracksdk.domain.model.home_model.response

import androidx.annotation.Keep


//TODO update type
@Keep
data class HomeDashboardResponseModel(
    var IsAssociate: Int? = 0,
    var IsGPSAttendance: Int? = 0,
    var ShowAwakeTracking: String? = "",
    var IsChatBoardEnabled: Int? = 0,
    var IMEIStatus: String? = "",
    var IMEI: String? = "",
    var CandidateID: String? = "",
    var AssociateID: String? = "",
    var InnovID: String? = "",
    var FirstName: String? = "",
    var MiddleName: String? = "",
    var LastName: String? = "",
    var DOB: String? = "",
    var MobileNo: String? = "",
    var Image: String? = "",
    var ChecksumValue: String? = "",
    var ProfilePercentage: Int? = 0,
    var IsCheckSum: Int? = 0,
    var AttendanceFromAnyWhere: Int? = 0,
    var LogYourVisit: String? = "",
    var RegID: String? = "",
    var GnetAssociateID: String? = "",
    var Isjoiningpending: String? = "",
    var DateofJoining: String? = "",
    var EmergencyContactName: String? = "",
    var EmergencyContactNo: String? = "",
    var ActualDOJ: String? = "",
    var IsDigiTracResignation: Int? = 0,
    var IsDigiTracReimbursement: Int? = 0,
    var IsAttendanceCamera: Int? = 0,
    var ClientID: String? = "",
    var NotificationCount: Int? = 0,
    var onboardingStatus: String? = "",
    var Letters: String? = "",
    var IsAssociateID: Int? = 0,
    var IsCustomeridCard: Int? = 0,
    var IsInnovIdCard: Int? = 0,
    var IsLeave: Int? = 0,
    var IsTraining: Int? = 0,
    var IsClientPolicies: Int? = 0,
    var IsDocumentDownLoad: Int? = 0,
    var DailyMileageLimit: String? = "",
    var DailyMileageFourWheelar: String? = "",
    var AllowForAttendance: String? = "",
    var LastWorkingDate: String? = "",
    var ReimbursementAllowDays: String? = "",
    var IsPendingReimbursement: Int? = 0,
    var IsPendingReimbursementNew: Int? = 0,
    var IsViewPayouts: Int? = 0,
    var IsNewReimbursement: Int? = 0,
    var IsIncomeTaxDeclaration: Int? = 0,
    var status: String? = "",
    var Message: String? = "",
    var geoTracking : Int?=0,
    var IsRefyneApplicable : Int?=0,
    var IsPaySlip : Int?=0,
    var IsAadharVerification :String?="",
    var IsPANVerification :String?="",
    var IsBankVerification :String?="",
    var NewResignationDD: Int? = 0,
    var QuickRegularization : Int?=0 ,
    var QuickAttendance : Int?=0,
    var SurveyPopup : Int?=0,
    var AllowPopUpClosed : Int?=0,
    var IsRewardsVisible : Int? = 0,

)

@Keep
data class HomeDashboardRequestModel(
    var IMEI: String? = "",
    var InnovID: String? = "",
)
